name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/awsphp

            git pull origin main

            docker stop php-app || true
            docker rm php-app || true

            docker build -t awsphp .

            docker run -d \
              -p 80:80 \
              --name php-app \
              awsphp